# Generated by Django 5.1.6 on 2025-02-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='preco',
        ),
        migrations.AddField(
            model_name='product',
            name='imagem',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
