# Generated by Django 5.1.7 on 2025-03-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('day', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('local', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
