# Generated by Django 5.1.7 on 2025-03-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('student_age', models.PositiveIntegerField()),
                ('student_course', models.CharField(max_length=50)),
                ('student_instituition', models.CharField(choices=[('Roberto Mange', 'Roberto Mange'), ('Maria Matosinho', 'Maria Matosinho')], max_length=100)),
                ('rm', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
